dist: xenial
language: cpp
os:
  - linux
arch:
  - ppc64le
compiler:
  - clang
  - gcc
services:
  - docker

install:
  - sudo apt-get install -y openjdk-8-jdk || exit $?
  - export PATH=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)/bin:$PATH
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)
  - echo "JAVA_HOME=${JAVA_HOME}"
  - which java && java -version
  - which javac && javac -version

script:
  - make jclean clean rocksdbjavastaticdockerppc64le
